name: Deploy to GitHub Pages

# Quando executar (push na branch main)
on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

# Etapas
jobs:

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      # Clonar repositório
      - name: Checkout
        uses: actions/checkout@v4
      # Configura o GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5
      # Faz upload dos arquivos
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Subir todos os arquivos do diretório atual
          path: '.'
      # Publica no GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
